-- ============================================================
-- FOODEE - Start ORDER_ITEMS Incremental Batch
-- ============================================================

INSERT INTO FOODEE_DB.RAW.FOODEE_BATCH_CONTROL
(
    RUN_ID,
    PROCESS_NAME,
    OLD_WATERMARK,
    BATCH_END_TIMESTAMP,
    CREATED_AT
)
SELECT
    UUID_STRING(),
    'ORDER_ITEMS',
    c.LAST_SUCCESSFUL_TIMESTAMP,
    MAX(r.LAST_UPDATED_TIMESTAMP),
    CURRENT_TIMESTAMP()
FROM FOODEE_DB.RAW.FOODEE_LOAD_CONTROL c
CROSS JOIN FOODEE_DB.RAW.RAW_ORDER_ITEMS r
WHERE c.PROCESS_NAME = 'ORDER_ITEMS'
GROUP BY c.LAST_SUCCESSFUL_TIMESTAMP;


-- Verify the batch
SELECT *
FROM FOODEE_DB.RAW.FOODEE_BATCH_CONTROL
WHERE PROCESS_NAME = 'ORDER_ITEMS'
ORDER BY CREATED_AT DESC
LIMIT 1;