-- ============================================================
-- FOODEE - Strengthen Batch Control
-- ============================================================

ALTER TABLE FOODEE_DB.RAW.FOODEE_BATCH_CONTROL
ADD COLUMN IF NOT EXISTS STATUS VARCHAR;

ALTER TABLE FOODEE_DB.RAW.FOODEE_BATCH_CONTROL
ADD COLUMN IF NOT EXISTS COMPLETED_AT TIMESTAMP_NTZ;

ALTER TABLE FOODEE_DB.RAW.FOODEE_BATCH_CONTROL
ADD COLUMN IF NOT EXISTS ERROR_MESSAGE VARCHAR;

ALTER TABLE FOODEE_DB.RAW.FOODEE_BATCH_CONTROL
ADD COLUMN IF NOT EXISTS ROWS_PROCESSED NUMBER;

ALTER TABLE FOODEE_DB.RAW.FOODEE_BATCH_CONTROL
ADD COLUMN IF NOT EXISTS ROWS_LOADED NUMBER;