-- ============================================================
-- FOODEE - Complete ORDER_ITEMS Batch
-- ============================================================

UPDATE FOODEE_DB.RAW.FOODEE_BATCH_CONTROL
SET
    STATUS = 'SUCCESS',
    COMPLETED_AT = CURRENT_TIMESTAMP(),

    ROWS_PROCESSED = (
        SELECT COUNT(*)
        FROM FOODEE_DB.RAW.RAW_ORDER_ITEMS r
        WHERE r.LAST_UPDATED_TIMESTAMP > OLD_WATERMARK
          AND r.LAST_UPDATED_TIMESTAMP <= BATCH_END_TIMESTAMP
    ),

    ROWS_LOADED = (
        SELECT COUNT(*)
        FROM FOODEE_DB.STAGE.STG_ORDER_ITEMS s
        WHERE s.LAST_UPDATED_TIMESTAMP > OLD_WATERMARK
          AND s.LAST_UPDATED_TIMESTAMP <= BATCH_END_TIMESTAMP
    )

WHERE RUN_ID = (
    SELECT RUN_ID
    FROM FOODEE_DB.RAW.FOODEE_BATCH_CONTROL
    WHERE PROCESS_NAME = 'ORDER_ITEMS'
    ORDER BY CREATED_AT DESC
    LIMIT 1
);

-- Verify the completed batch
SELECT *
FROM FOODEE_DB.RAW.FOODEE_BATCH_CONTROL
WHERE PROCESS_NAME = 'ORDER_ITEMS'
ORDER BY CREATED_AT DESC
LIMIT 1;