-- ============================================================
-- FOODEE - Audit Successful ORDER_ITEMS Batch
-- ============================================================

INSERT INTO FOODEE_DB.RAW.FOODEE_PIPELINE_AUDIT
(
    RUN_ID,
    PROCESS_NAME,
    TABLE_NAME,
    LAYER,
    START_TIME,
    END_TIME,
    ROWS_PROCESSED,
    ROWS_LOADED,
    STATUS,
    ERROR_MESSAGE
)
SELECT
    RUN_ID,
    PROCESS_NAME,
    'ORDER_ITEMS',
    'RAW_TO_PUB',
    CREATED_AT,
    COMPLETED_AT,
    ROWS_PROCESSED,
    ROWS_LOADED,
    STATUS,
    ERROR_MESSAGE
FROM FOODEE_DB.RAW.FOODEE_BATCH_CONTROL
WHERE RUN_ID = (
    SELECT RUN_ID
    FROM FOODEE_DB.RAW.FOODEE_BATCH_CONTROL
    WHERE PROCESS_NAME = 'ORDER_ITEMS'
    ORDER BY CREATED_AT DESC
    LIMIT 1
)
AND STATUS = 'SUCCESS';

-- Verify audit record
SELECT *
FROM FOODEE_DB.RAW.FOODEE_PIPELINE_AUDIT
WHERE PROCESS_NAME = 'ORDER_ITEMS'
ORDER BY START_TIME DESC
LIMIT 1;